routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Auth::routes();

Auth::routes(['register' => false]);

Route::group(['middleware' => ['auth']], function () {
    
    Route::get('/employees', 'HomeController@index')->name('employees');

    Route::resource('employees','EmployeeController');

    Route::resource('companies','CompaniesController');
});

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Companies;
use Illuminate\Http\Request;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Companies::latest()->paginate(10);
  
        return view('companies.index',compact('companies'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|unique:companies|email',
            'logo' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'web_site' => 'required|url',
        ]);
  
        $company = Companies::create($request->all());

        if(\Request::hasFile('logo')) {
            $file = \Request::file('logo');
            $exten = $file->getClientOriginalExtension();
            $rand = date('Ymdhms');
            $file_name = "logo_".$rand.$request->vendor_code.".".$exten;
            $file->move(public_path().'/storage/app/public/',$file_name);  
            $company->logo = $file_name;
            $company->save();
        }
   
        return redirect()->route('companies.index')
                        ->with('success','Company profile created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function show(Companies $company)
    {
        return view('companies.show',compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function edit(Companies $company)
    {
        return view('companies.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Companies $company)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required|email',
            //'logo' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'web_site' => 'required|url',
        ]);

        $company->update($request->all());
        
        if(\Request::hasFile('logo')) {
            $file = \Request::file('logo');
            $exten = $file->getClientOriginalExtension();
            $rand = date('Ymdhms');
            $file_name = "logo_".$rand.$request->vendor_code.".".$exten;
            $file->move(public_path().'/storage/app/public/',$file_name);  
            $company->logo = $file_name;
            $company->save();
        }
        
   
        return redirect()->route('companies.index')
                        ->with('success','Company profile updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Companies  $companies
     * @return \Illuminate\Http\Response
     */
    public function destroy(Companies $companies)
    {
        $companies->delete();
  
        return redirect()->route('companies.index')
                        ->with('success','Company deleted successfully');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create Page </h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('companies.index') }}">  <i class="fa fa-chevron-left" aria-hidden="true"></i></a>
        </div>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('companies.store') }}" method="POST" style="padding: 10px 50px 0px 50px;" enctype="multipart/form-data">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>E-mail:</strong>
                <input type="text" name="email" class="form-control" placeholder="Email">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Profile:</strong>
                <input type="file" name="logo" class="form-control" placeholder="Profile">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Web Site:</strong>
                <input type="text" name="web_site" class="form-control" placeholder="Web site">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Company</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('companies.index') }}"> <i class="fa fa-chevron-left" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('companies.update',$company->id) }}" method="POST" style="padding: 10px 50px 0px 50px;" enctype="multipart/form-data">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $company->name }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>E-mail:</strong>
                    <input type="text" name="email" value="{{ $company->email }}" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Profile:</strong>
                    <input type="file" name="logo" value="{{ $company->logo }}" class="form-control" placeholder="Profile">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Web Site:</strong>
                    <input type="text" name="web_site" value="{{ $company->web_site }}" class="form-control" placeholder="Web Site">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')
 
@section('content')

    <ul class="navbar-nav mr-auto">

    <li style="padding: 10px 10px 10px 10px;">  <a class="btn btn-info" href="{{ url('employees') }}">Employees</a> </li>
    </ul>


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Companies Info</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('companies.create') }}"> <i class="fa fa-plus-circle" aria-hidden="true"></i> New Company</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Profile</th>
            <th>Web Site</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($companies as $company)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $company->name }}</td>
            <td>{{ $company->email }}</td>
            <td><img style="margin-left:25px;border-radius: 50%;" src="/storage/app/public/{{$company->logo}}" width="40" height="40" /></td>
            <td>{{ $company->web_site }}</td>
            <td>
                <form action="{{ route('companies.destroy',$company->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('companies.show',$company->id) }}"><i class="fa fa-eye" aria-hidden="true"></i></a>
    
                    <a class="btn btn-primary" href="{{ route('companies.edit',$company->id) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o" aria-hidden="true"></i></button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $companies->links() !!}
      
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Company</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('companies.index') }}"> <i class="fa fa-chevron-left" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
   
    <div class="row" style="padding: 10px 50px 0px 50px;">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $company->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>E-mail:</strong>
                {{ $company->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Profile:</strong>
                <img style="margin-left:25px;border-radius: 50%;" src="/storage/app/public/{{$company->logo}}" width="100" height="100" />
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Web Site:</strong>
                {{ $company->web_site }}
            </div>
        </div>
    </div>
@endsection